import = [
  "~/.dotfiles/alacritty/themes/themes/catppuccin.toml"
]

[env]
term = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14



[keyboard]
bindings = [
  # Enable support for 'Option/Alt + 3' to produce # for UK keyboard layout
  { key = "Key3", mods = "Alt",chars = "#"}
]
